// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"rApp/tsrApp/clients/sdtm/client/a1_e_i_registration"
	"rApp/tsrApp/clients/sdtm/client/data_consumer"
	"rApp/tsrApp/clients/sdtm/client/data_producer_registration"
	"rApp/tsrApp/clients/sdtm/client/s_d_t_m_api_definition"
	"rApp/tsrApp/clients/sdtm/client/service_discovery_apis"
	"rApp/tsrApp/clients/sdtm/client/service_expose_api"
	"rApp/tsrApp/clients/sdtm/client/service_heart_beat"
	"rApp/tsrApp/clients/sdtm/client/service_registration_apis"
	"rApp/tsrApp/clients/sdtm/client/service_status"
)

// Default sdtm HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "localhost"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"http", "https"}

// NewHTTPClient creates a new sdtm HTTP client.
func NewHTTPClient(formats strfmt.Registry) *Sdtm {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new sdtm HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *Sdtm {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new sdtm client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Sdtm {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(Sdtm)
	cli.Transport = transport

	cli.A1EIRegistration = a1_e_i_registration.New(transport, formats)

	cli.DataConsumer = data_consumer.New(transport, formats)

	cli.DataProducerRegistration = data_producer_registration.New(transport, formats)

	cli.SDTMAPIDefinition = s_d_t_m_api_definition.New(transport, formats)

	cli.ServiceDiscoveryApis = service_discovery_apis.New(transport, formats)

	cli.ServiceExposeAPI = service_expose_api.New(transport, formats)

	cli.ServiceHeartBeat = service_heart_beat.New(transport, formats)

	cli.ServiceRegistrationApis = service_registration_apis.New(transport, formats)

	cli.ServiceStatus = service_status.New(transport, formats)

	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// Sdtm is a client for sdtm
type Sdtm struct {
	A1EIRegistration *a1_e_i_registration.Client

	DataConsumer *data_consumer.Client

	DataProducerRegistration *data_producer_registration.Client

	SDTMAPIDefinition *s_d_t_m_api_definition.Client

	ServiceDiscoveryApis *service_discovery_apis.Client

	ServiceExposeAPI *service_expose_api.Client

	ServiceHeartBeat *service_heart_beat.Client

	ServiceRegistrationApis *service_registration_apis.Client

	ServiceStatus *service_status.Client

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *Sdtm) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport

	c.A1EIRegistration.SetTransport(transport)

	c.DataConsumer.SetTransport(transport)

	c.DataProducerRegistration.SetTransport(transport)

	c.SDTMAPIDefinition.SetTransport(transport)

	c.ServiceDiscoveryApis.SetTransport(transport)

	c.ServiceExposeAPI.SetTransport(transport)

	c.ServiceHeartBeat.SetTransport(transport)

	c.ServiceRegistrationApis.SetTransport(transport)

	c.ServiceStatus.SetTransport(transport)

}
